### PR TITLE
Added `toidentifier` package

### PR DESCRIPTION
**Pull request by niftylettuce**
Hi @dougwilson.  I've added you as an npm owner and also published the repo for this package under the @koajs organization at <https://github.com/koajs/toidentifier> (you have admin there as well; if you want to move it to `jshttp` go for it!).  I also ensured that it also had the same Node versions to test against.  I needed this function outside of this project so I figured I'd put it into a package.  Hope this helps.  Thanks!

### CODE REVIEW

**Comment by dougwilson** [comment]
Awesome, thanks for this @niftylettuce ! Sorry I didn't see it early for some reason. Definitely makes sense to include here 👍 So for where the package belongs -- it doesn't really fit in any of our orgs (jshttp, pillarjs, expressjs) since it's just a string utility function. You're welcome to keep the module under our own personal GitHub account (I don't mind using those types of modules, especially simplistic ones), or I can add you as an owner to https://github.com/component if you want to move it there (even though component itself is abandoned, the org is useful for collecting utilities).

**Comment by niftylettuce** [comment]
Yeah that's cool with me @dougwilson

**Comment by niftylettuce** [comment]
@dougwilson who should I add on NPM for it?  is there an org?

**Comment by niftylettuce** [comment]
Repo moved: https://github.com/component/toidentifier

**Comment by dougwilson** [comment]
There isn't any org on npm I know of; you're free to add me to it if you like. Adding @jonathanong is also a good backup too if you're looking for another 👍

**Comment by niftylettuce** [comment]
done @dougwilson, added jongleberry and dougwilson npm users

**Comment by dougwilson** [comment]
Ok, no wonder why I didn't see this before. I never got an email for your comment https://github.com/jshttp/http-errors/pull/44#issuecomment-363990847 nor https://github.com/jshttp/http-errors/pull/44#issuecomment-363990024 just now, eve though I got others in this thread and other threads during this (but also missed some emails during this). There must be a GitHub issue with sporadic emails or something.

**Pull request merged**
