### PR TITLE
Release 2.0

### PR DESCRIPTION
**Pull request by dougwilson**
This is a tracking issue for release 2.0.

**Please keep feature requests in their own issues**

If you want to make a comment on a particular change, please make the comment in the "Files changed" tab so comments are not lost during a rebase.

List of changes for release:
- [x] Drop support for Node.js 0.6
- [x] Remove deprecated "I'mateapot" export
- [x] Remove support for status being non-first argument #76
- [x] Upgrade `depd` to 2.0 #72 
- [x] Upgrade `statuses` to 2.0

**Testing this release**

If you want to try out this release, you can install it with the following commands:

``` bash
$ npm cache clean http-errors
$ npm install jshttp/http-errors#2.0
```

**Please do not merge until there is some kind of consensus / non-objection**

### CODE REVIEW

**Comment by jimmywarting** [comment]
long over due? time for a major release soon?

also think you should drop some lower node versions as well and go for something like v12+ only
but that's just my opinion...

**Comment by dougwilson** [comment]
Hi @jimmywarting thanks for the comment. The drop versions comment is interesting. If you would like to see that happen, can you list the specific benefits that would bring to the project? That would help weigh the cost of many of the projects that depend on this one being unable to simply upgrade without also dropping version support.

**Comment by jimmywarting** [comment]
> If you would like to see that happen, can you list the specific benefits that would bring to the project? 

it's just about new code standards/trends 

some ppl are drawn away from old code style that they don't want to contribute to a package that they just decide to fork it instead. cuz getting some PR that you have done for someone is hard when they are rejected for not being node v0.8 compatible. Many PRs (and issues) in the projects you own have already been rejected b/c of it that is why i stop helping and sending out PRs to you or not even bordered to make any issues) 

If i'm restricted from using any of the 80% of the new features that is new and i have to support something like IE7 still then i would just quit my job and look for a new one. I don't want to have to think about thinks like "can i use `[].includes(x)` or must i use the old `[].indexOf(x) >= 0`, can i use for..of or am i stuck with classic for loops?

I can't remember the last time i used node's `util.inherits` and have basically forgotten all about it and the prototyping stuff and making sure you called the function using the new keyword. if you didn't do it then the code handles dose cases for you sometimes like `if (!(this instanceof Foo)) return new Foo()` it it's just bad code smell

nowadays i just do `class Foo extends Bar {}` in new project. NodeJS even marked [inherits as legacy](https://nodejs.org/docs/latest-v17.x/api/util.html#utilinheritsconstructor-superconstructor) and recommend you to use classes instead.

I get it that you want to support super old enviornments but i also think that brings fewer who are willing to contribute to such projects

if i could (and if i owned this project) i would have:
- removed inherit
- switch to classes
- used optional chaining
- used default values in arguments
- used rest/spred arguments 
- change to const/let
- switch to esm-only (would require v12.20) so that that it can be imported into Deno as well
- used private fields or weakmap for truly private stuff
- remove all deprecated function
- make a major release and only support the 3 latest LTS versions (currently 12, 14 and 16)

This would make the code smaller and more modern with even fewer dependencies

but that is too much to ask for by someone who still targets node version as low as v0.8 still

By using classes instead of doing stuff with prototype+inherits you gain some good IDE autocompletion from VScode

By supporting very old nodejs version then you are allowing it to persist and and ppl will never update there nodejs version that have plenty of security vulnerabilities.

it also makes it hard to bring in any new dependency that only target higher environments. and some of your dependencies are stuck with super old version cuz they have breaking changes that requires a newer node version. so if you depend on the same pkg then you have duplication all over the place

---

Sry if this would comes out harsh to you, I get some harsh comments sometimes myself for being somewhat popular in the open source community and not doing some stuff in a certain way. If i don't have anything good to say and they are only complains then i most often keep them to myself. but you asked for my opinions, so there you have them. I hope you do not take this badly. I Love all the things you have contributed into open source and i use many of your stuff without even noticing it

**Comment by jimmywarting** [comment]
your most commented issue in express is [Should Express 5.0 require a minimum of Node.js 4?
](https://github.com/expressjs/express/issues/2755) so no wonder why they want things to be more modernized and why they turn to other things instead

i unsubscribed to it cuz i realised that it will never likely happen any time soon, the issue was created in 2015 so, if it haven't been resolved in 6 years, why would it see any light of day in any near feature?

**Comment by dougwilson** [comment]
Hi @jimmywarting I appreciate your response, but I'm going to hide it as it devolved into either personal attacks or just long rants without any specifics. Before your response, I looked at all the projects on npm that depend on this one. Almost every project that does and has an engines field has pne lower than 12 currently. I am always happy to help any specific PR use older syntax if that is necessary, including committing myself. It is also unfortunate that I have to run some servers that use older versions of Node.js. Just like there may br spme folks who may not contribute if they can not use the most newest syntax, even worse, I cannot maintain modules that I cannot myself use; by definition those would be forks anyhow.

**Comment by jimmywarting** [comment]
please, don't take it as personal attack, then i starts to feel bad for posting what i just wrote, it was more a long rant.

**Pull request merged**
