### PR TITLE
Add support for OSSF scorecard reporting

### PR DESCRIPTION
**Pull request by carpasse**
# Main Changes

This pipeline will proactively report the status of the project (every day and when a push is done to `master` branch) including critical fields (`CI-Tests`, `Contributors`, `Dependency-Update-Tool`, `Webhooks`) that are missing while running via OSSF cron jobs.

## Context

**Changes related**

It's also possible that some repositories in your organization are already being [automatically tracked](https://github.com/ossf/scorecard/blob/main/docs/faq.md#can-i-preview-my-projects-score) by OpenSSF in this [CSV file](https://github.com/ossf/scorecard/blob/main/cron/internal/data/projects.csv) via weekly cronjob. One caveat: Automatically tracked projects do not include https://github.com/ossf/scorecard/issues/3438 in their analysis (CI-Tests,Contributors,Dependency-Update-Tool,Webhooks).

Source: [openssf-scorecard-monitor documentation](https://github.com/UlisesGascon/openssf-scorecard-monitor)

**Team discussion related**

Ref: https://github.com/expressjs/security-wg/issues/2
Report: https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/jshttp/http-errors/commit/206aa2c15635dc1212c06c279540972aa90e23ea

**Changelog**
c33f053aa26936cdcfc287d76748acf8da6bf9b6 chore: add scorecard pipeline by @carpasse

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM! Thanks for the work @carpasse.

I updated the report url in the PR description to https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/jshttp/http-errors/commit/206aa2c15635dc1212c06c279540972aa90e23ea as the previous one was pointing to express package 😉

**Comment by UlisesGascon** [comment]
The CI is failing due https://github.com/jshttp/http-errors/issues/108, and it is not related to this PR as the change does not affect the source code or the existing GA pipelines.

I will merge this PR on next Monday, unless there are concerns.

**Comment by jonchurch** [comment]
Not worth blocking on, but is there a reason to use this ad hoc workflow vs the official github action? Does this workflow do different things than the action or is otherwise preferred over the versioned and maintained action?

https://github.com/ossf/scorecard-action

**Comment by UlisesGascon** [comment]
> Not worth blocking on, but is there a reason to use this ad hoc workflow vs the official ossf github action? Does this workflow do different things than the action or is otherwise preferred over the versioned and maintained action?

We use the same one (official one), for reference: https://github.com/jshttp/http-errors/blob/937e72a80100af8c2d4140230abcf1c797facab9/.github/workflows/scorecard.yml#L40

```yml
      - name: "Run analysis"
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d # v2.0.6
        with:
          results_file: results.sarif
          results_format: sarif
```

**Pull request merged**
