### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by tkrotoff**
Consistency/bikeshedding

### CODE REVIEW

**Comment by tkrotoff** [comment]
[Node.js 0.6 and 0.8 builds](https://travis-ci.org/jshttp/http-errors/builds/88294107) fail because of dependencies, nothing related to the PR itself.

**Comment by dougwilson** [comment]
lol, forgot about this pull request. I'll merge :)

**Comment by tkrotoff** [comment]
Wow, I did not know you could change the commit messages from a PR, nice :)

**Comment by dougwilson** [comment]
haha, yea. Here is what I did, if you're interested:

1. GitHub has some buried secrets around it, including the fact that you can append `.patch` to a pull request URL and it'll be a git-formatted patch file. I then go into `git` command line on my machine and apply that patch using `git am`, with the following command: `curl -L https://github.com/jshttp/http-errors/pull/21.patch | git am`.
2. Then I make adjustments to the patch for nits, and then `git commit --amend` to alter the message for nits (and to add a link to the PR #, which of course you couldn't easily know before making the PR).

I hope that was OK :) ! I try to make it easy to accept PRs by just fixing up nits on merge instead of requiring radnom back-and-forth for "dumb reasons" :)

**Comment by tkrotoff** [comment]
Wow bis!

**Pull request closed without merging**
