### PR TITLE
List all constructors in the readme

### PR DESCRIPTION
**Pull request by tjmehta**
It's useful to see all the error constructors w/ their status codes for reference.

### CODE REVIEW

**Comment by olalonde** [comment]
+1

**Comment by dougwilson** [comment]
Thanks, @tjmehta, I think it's good to list them all :) I have a couple of issues with the pull request, though:

1. There are a lot listed that we don't even export, for example, all the 1xx, 2xx, and 3xx we don't have on our export, so we shouldn't document that we do :)
2. The formatting here seems a little weird, to put it in the example as `err` re-assigning. Perhaps make a table?

**Comment by tjmehta** [comment]
Sounds good, will update PR today

**Comment by dougwilson** [comment]
Sweet! Here is a little one liner I just slapped together that should help create the table:
```
$ node -pe 'var m={},e=require("http-errors");Object.keys(e).forEach(function(p){var c=isNaN(p)?e[p].prototype.status:p;if(c)m[c]=isNaN(p)?p:" "});Object.keys(m).forEach(function(c){console.log("|%s|%s|",c,m[c])})'
```

**Comment by tjmehta** [comment]
Hah, nice! Give me an hour then

**Comment by dougwilson** [comment]
```
$ node -e 'var l=4,m={},e=require("http-errors");Object.keys(e).forEach(function(p){var c=isNaN(p)?e[p].prototype.status:p;if(c&&!m[c]){m[c]=isNaN(p)?p:"";l=Math.max(l,m[c].length)}});r("code","name");r("----",d("","-"));Object.keys(m).forEach(function(c){r(c+" ",m[c])});function r(a,b){console.log("|%s|%s|",a,d(b))}function d(a,b){return a+(new Array(l-a.length+1)).join(b||" ")}'
|code|name                         |
|----|-----------------------------|
|400 |BadRequest                   |
|401 |Unauthorized                 |
|402 |PaymentRequired              |
|403 |Forbidden                    |
|404 |NotFound                     |
|405 |MethodNotAllowed             |
|406 |NotAcceptable                |
|407 |ProxyAuthenticationRequired  |
|408 |RequestTimeout               |
|409 |Conflict                     |
|410 |Gone                         |
|411 |LengthRequired               |
|412 |PreconditionFailed           |
|413 |PayloadTooLarge              |
|414 |URITooLong                   |
|415 |UnsupportedMediaType         |
|416 |RangeNotSatisfiable          |
|417 |ExpectationFailed            |
|418 |ImATeapot                    |
|421 |MisdirectedRequest           |
|422 |UnprocessableEntity          |
|423 |Locked                       |
|424 |FailedDependency             |
|425 |UnorderedCollection          |
|426 |UpgradeRequired              |
|428 |PreconditionRequired         |
|429 |TooManyRequests              |
|431 |RequestHeaderFieldsTooLarge  |
|451 |UnavailableForLegalReasons   |
|500 |InternalServerError          |
|501 |NotImplemented               |
|502 |BadGateway                   |
|503 |ServiceUnavailable           |
|504 |GatewayTimeout               |
|505 |HTTPVersionNotSupported      |
|506 |VariantAlsoNegotiates        |
|507 |InsufficientStorage          |
|508 |LoopDetected                 |
|509 |BandwidthLimitExceeded       |
|510 |NotExtended                  |
|511 |NetworkAuthenticationRequired|
```

**Comment by tjmehta** [comment]
How does this look::

### new createError\[code || name\](\[msg]\))

```js
var err = new createError.NotFound();
```

- `code` - the status code as a number
- `name` - the name of the error as a "bumpy case", i.e. `NotFound` or `InternalServerError`.

#### List of all constructors

| Status Code   | Constructor   |
| ------------- | ------------- |
|400|BadRequest|
|401|Unauthorized|
|402|PaymentRequired|
|403|Forbidden|
|404|NotFound|
|405|MethodNotAllowed|
|406|NotAcceptable|
|407|ProxyAuthenticationRequired|
|408|RequestTimeout|
|409|Conflict|
|410|Gone|
|411|LengthRequired|
|412|PreconditionFailed|
|413|PayloadTooLarge|
|414|URITooLong|
|415|UnsupportedMediaType|
|416|RangeNotSatisfiable|
|417|ExpectationFailed|
|418|I'mateapot|
|422|UnprocessableEntity|
|423|Locked|
|424|FailedDependency|
|425|UnorderedCollection|
|426|UpgradeRequired|
|428|PreconditionRequired|
|429|TooManyRequests|
|431|RequestHeaderFieldsTooLarge|
|451|UnavailableForLegalReasons|
|500|InternalServerError|
|501|NotImplemented|
|502|BadGateway|
|503|ServiceUnavailable|
|504|GatewayTimeout|
|505|HTTPVersionNotSupported|
|506|VariantAlsoNegotiates|
|507|InsufficientStorage|
|508|LoopDetected|
|509|BandwidthLimitExceeded|
|510|NotExtended|
|511|NetworkAuthenticationRequired|

**Comment by dougwilson** [comment]
Looks pretty rad

**Comment by tjmehta** [comment]
Updated

**Comment by dougwilson** [comment]
Thanks much!

**Pull request closed without merging**
